export const ICONS = {
    "eye-closed": "material-symbols:visibility-off-outline-rounded",
    "eye-open": "material-symbols:visibility-outline-rounded",
    "chevron-down": "material-symbols:expand-more-rounded",
    "chevron-up": "material-symbols:expand-less-rounded",
    "chevron-right": "material-symbols:chevron-right-rounded",
    "arrow-up": "solar:arrow-up-linear",
    "arrow-down": "solar:arrow-down-linear",
    "arrow-left": "solar:arrow-left-linear",
    "arrow-right": "solar:arrow-right-linear",
    "3dots": "bi:three-dots",
    scissors: "solar:scissors-linear",
    house: "material-symbols-light:home-outline-rounded",
    copy: "nimbus:copy",
    paste: "fluent:clipboard-paste-24-regular",
    // share: "solar:share-linear",
    share: "mdi-light:share",
    clock: "ic:round-access-time",
    star: "material-symbols:kid-star-outline",
    filter: "mdi:filter-outline",
    details: "material-symbols-light:library-books-outline",
    delete: "material-symbols:delete-outline",
    sort: "lsicon:sort-filter-filled",
    circle: "svg-spinners:ring-resize",
    spinner: "svg-spinners:6-dots-rotate",
    online: "material-symbols:wifi",
    offline: "carbon:cloud-offline",
    globe: "solar:global-outline",
    "battery-charging": "bi:battery-charging",
    battery: "bi:battery-full",
    "battery-half": "bi:battery-half",
    "volume-off": "bi:volume-mute",
    "volume-low": "bi:volume-down",
    "volume-high": "bi:volume-up",
    notification: "material-symbols:notifications-outline-rounded",
    minimize: "codicon:chrome-minimize",
    maximize: "material-symbols:chrome-maximize-outline-sharp",
    restore: "cil:window-restore",
    close: "material-symbols:close-rounded",
    "plus-r": "material-symbols:add-2-rounded",
    search: "material-symbols:search-rounded",
    refresh: "material-symbols:refresh-rounded",
};

export const SVG = {};
