export const ICONS = {
    "eye-closed": "material-symbols:visibility-off-outline-rounded",
    "eye-open": "material-symbols:visibility-outline-rounded",
    "chevron-down": "material-symbols:expand-more",
    "chevron-up": "material-symbols:expand-less",
    "arrow-left": "material-symbols:arrow-left-alt-rounded",
    circle: "svg-spinners:ring-resize",
    spinner: "svg-spinners:6-dots-rotate",
    online: "material-symbols:wifi",
    offline: "carbon:cloud-offline",
    globe: "solar:global-outline",
    "battery-charging": "bi:battery-charging",
    battery: "bi:battery-full",
    "battery-half": "bi:battery-half",
    "volume-off": "bi:volume-mute",
    "volume-low": "bi:volume-down",
    "volume-high": "bi:volume-up",
    notification: "material-symbols:notifications-outline-rounded",
    minimize: "codicon:chrome-minimize",
    maximize: "material-symbols:chrome-maximize-outline-sharp",
    restore: "cil:window-restore",
    close: "material-symbols:close",
    "plus-r": "material-symbols:add-2-rounded",
    search: "material-symbols:search-rounded",
    refresh: "material-symbols:refresh-rounded",
} as const;
