export const ICONS = {
    "eye-closed": "material-symbols:visibility-off-outline-rounded",
    "eye-open": "material-symbols:visibility-outline-rounded",
    "chevron-down": "material-symbols:expand-more-rounded",
    "chevron-up": "material-symbols:expand-less-rounded",
    "chevron-right": "material-symbols:chevron-right-rounded",
    "arrow-up": "solar:arrow-up-linear",
    "arrow-down": "solar:arrow-down-linear",
    "arrow-left": "solar:arrow-left-linear",
    "arrow-right": "solar:arrow-right-linear",
    "3dots": "bi:three-dots",
    scissors: "fluent:cut-32-regular",
    house: "material-symbols-light:home-outline-rounded",
    rename: "fluent:rename-a-20-regular",
    copy: "fluent:copy-16-regular",
    paste: "fluent:clipboard-paste-24-regular",
    share: "fluent:share-16-regular",
    clock: "ic:round-access-time",
    star: "material-symbols:kid-star-outline",
    filter: "mdi:filter-outline",
    details: "material-symbols-light:library-books-outline",
    delete: "material-symbols:delete-outline",
    sort: "lsicon:sort-filter-filled",
    list: "fluent:apps-list-32-regular",
    circle: "svg-spinners:ring-resize",
    spinner: "svg-spinners:6-dots-rotate",
    online: "fluent:wifi-1-20-filled",
    // offline: "carbon:cloud-offline",
    offline: "fluent:wifi-off-20-filled",
    globe: "solar:global-outline",
    "battery-charging": "fluent:battery-charge-2-20-regular",
    "battery-f-charging": "fluent:battery-charge-9-20-regular",
    battery: "fluent:battery-0-20-filled",
    "battery-half": "fluent:battery-6-32-regular",
    // "volume-off": "fluent:speaker-0-32-regular",
    "volume-off": "fluent:speaker-mute-32-regular",
    "volume-low": "fluent:speaker-1-32-regular",
    "volume-high": "fluent:speaker-2-32-regular",
    notification: "material-symbols:notifications-outline-rounded",
    minimize: "codicon:chrome-minimize",
    maximize: "material-symbols:chrome-maximize-outline-sharp",
    restore: "cil:window-restore",
    close: "material-symbols:close-rounded",
    "plus-r": "material-symbols:add-2-rounded",
    "plus-circle": "mdi:plus-circle-outline",
    search: "material-symbols:search-rounded",
    refresh: "material-symbols:refresh-rounded",
    preview: "codicon:open-preview",
};

export const SVG = {};
