export const ICONS = {
    'eye-closed': 'i-material-symbols:visibility-off-outline-rounded',
    'eye-open': 'i-material-symbols:visibility-outline-rounded',
    'chevron-down': 'material-symbols:expand-more',
    'chevron-up': 'material-symbols:expand-less',
    'arrow-left': 'material-symbols:arrow-left-alt-rounded',
    'circle': 'i-svg-spinners:ring-resize',
    'spinner': 'i-svg-spinners:6-dots-rotate',
    'online': 'i-material-symbols:wifi-sharp',
    'offline': 'i-carbon:cloud-offline',
    'globe': 'i-solar:global-outline',
    'battery-charging': 'i-bi:battery-charging',
    'battery': 'i-bi:battery-full',
    'battery-half': 'i-bi:battery-half',
    'volume-off': 'i-bi:volume-mute',
    'volume-low': 'i-bi:volume-down',
    'volume-high': 'i-bi:volume-up',
    'notification': 'i-material-symbols:notifications-outline-rounded',
    'minimize': 'i-codicon:chrome-minimize',
    'maximize': 'i-material-symbols:chrome-maximize-outline-sharp',
    'restore': 'i-cil:window-restore',
    'close': 'i-material-symbols:close'
} as const